# Assignment: Preparing Data for Analysis (Modified Titanic)

![](https://github.com/kaopanboonyuen/2110446_DataScience_2021s2/raw/main/%20files/hw.png)

# 1) Load data & review the data

How many rows are there in the "titanic_to_student.csv"?

In [1]:
#Import the libraries
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('titanic_to_student.csv')

In [36]:
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Embarked
0,0,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,PC 17599,71.2833,C
1,1,4,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,113803,53.1000,S
2,2,6,0.0,3.0,"Moran, Mr. James",male,NaN,0.0,330877,8.4583,Q
3,3,8,0.0,3.0,"Palsson, Master. Gosta Leonard",male,2.0,3.0,349909,21.0750,S
4,4,10,1.0,2.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1.0,237736,30.0708,C

In [3]:
df = df.set_index('PassengerId')

In [4]:
df.shape[0]

445

# 2) Drop unqualified variables
2.1 Drop variables with missing > 50%

2.2 Check all columns except 'Age' and 'Fare' for flat values, drop the columns where flat value > 70%
From 2.1 and 2.2, how many columns do we have left?

Note: 
    
    -Ensure missing values are considered in your calculation. If you use normalize in .value_counts(), please include dropna=False.

In [8]:
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0,PC 17599,71.2833,C85,C
1,1,4,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0,113803,53.1000,C123,S
2,2,6,0.0,3.0,"Moran, Mr. James",male,NaN,0.0,0,330877,8.4583,NaN,Q
3,3,8,0.0,3.0,"Palsson, Master. Gosta Leonard",male,2.0,3.0,1,349909,21.0750,NaN,S
4,4,10,1.0,2.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1.0,0,237736,30.0708,NaN,C

## 2.1

In [5]:
df.isna().sum(axis=0)/df.shape[0] > 0.5

Unnamed: 0    False
Survived      False
Pclass        False
Name          False
Sex           False
Age           False
SibSp         False
Parch         False
Ticket        False
Fare          False
Cabin          True
Embarked      False
dtype: bool

In [6]:
df = df.drop(axis=1, labels=['Cabin'])

In [7]:
df.columns

Index(['Unnamed: 0', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

## 2.2

In [8]:
(df['Ticket'].value_counts(dropna=False) / df.shape[0]).max()

np.float64(0.04269662921348315)

In [10]:
flagged = []
for feat in df.columns:
    max_unique = (df[feat].value_counts(dropna=False) / df.shape[0]).max()
    if max_unique > 0.7:
        flagged.append(feat)

In [11]:
flagged

['Parch']

In [12]:
df = df.drop(labels=flagged, axis=1)

In [13]:
print('Left with',df.shape[1],'cols')

Left with 10 cols

# 3) Remove all rows with missing target (the variable "Survived")

Remove all rows with missing targets (the variable "Survived")

How many rows do we have left?

In [14]:
df = df[~df['Survived'].isna()]

In [15]:
df.shape[0]

432

# 4) Handle outliers 
Handle outliers

For the variable “Fare”, replace outlier values with the boundary values

If value < (Q1 - 1.5IQR), replace with (Q1 - 1.5IQR)

If value > (Q3 + 1.5IQR), replace with (Q3 + 1.5IQR)

What is the average (mean) of “Fare” after replacing the outliers (round 2 decimal points)?

Hint: Use function round(_, 2)

In [21]:
quartiles = df['Fare'].quantile([0.25,0.5,0.75])
quartiles

0.25     7.91770
0.50    15.24580
0.75    34.10935
Name: Fare, dtype: float64

In [22]:
iqr = quartiles[0.75] - quartiles[0.25]

In [23]:
lower = quartiles[0.25] - 1.5*iqr
upper = quartiles[0.75] + 1.5*iqr

In [24]:
df['Fare'] = df['Fare'].clip(lower=lower, upper=upper)

In [25]:
round(df['Fare'].mean(),2)

np.float64(26.23)

# 5) Impute missing value

Impute missing value

For number type column, impute missing values with mean

What is the average (mean) of “Age” after imputing the missing values (round 2 decimal points)?

Hint: Use function round(_, 2)

In [26]:
df.columns

Index(['Unnamed: 0', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [27]:
df.head()

,Unnamed: 0,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Embarked
PassengerId,,,,,,,,,,
2,0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,PC 17599,71.2833,C
4,1,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,113803,53.1000,S
6,2,0.0,3.0,"Moran, Mr. James",male,NaN,0.0,330877,8.4583,Q
8,3,0.0,3.0,"Palsson, Master. Gosta Leonard",male,2.0,3.0,349909,21.0750,S
10,4,1.0,2.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1.0,237736,30.0708,C

In [28]:
number_cols = ['Age','Fare', 'SibSp']

In [29]:
for col in number_cols:
    df.loc[df[col].isna(), col] = df[col].mean()

In [30]:
df['Age'].mean()

np.float64(29.332636103151863)

# 6) Convert categorical to numeric values

Convert categorical to numeric values

For the variable “Embarked”, perform the dummy coding.

What is the average (mean) of “Embarked_Q” after performing dummy coding (round 2 decimal points)?

Hint: Use function round(_, 2)

In [ ]:
df.head()

,Unnamed: 0,Survived,Pclass,Name,Sex,Age,SibSp,Ticket,Fare,Embarked
PassengerId,,,,,,,,,,
2,0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1.0,PC 17599,71.2833,C
4,1,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1.0,113803,53.1000,S
6,2,0.0,3.0,"Moran, Mr. James",male,29.332636,0.0,330877,8.4583,Q
8,3,0.0,3.0,"Palsson, Master. Gosta Leonard",male,2.000000,3.0,349909,21.0750,S
10,4,1.0,2.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1.0,237736,30.0708,C

In [38]:
cat_col = ['Sex', 'Embarked']
for col in cat_col:
    if col == 'Sex':
        df[col] = df[col].astype('category').cat.codes
    else:
        df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

In [39]:
df['Embarked_Q'].mean().round(2)

np.float64(0.06)

# 7) Partition data
Split train/test split with stratification using 70%:30% and random seed with 123

Show a proportion between survived (1) and died (0) in all data sets (total data, train, test)

What is the proportion of survivors (survived = 1) in the training data (round 2 decimal points)?

Hint: Use function round(_, 2), and train_test_split() from sklearn.model_selection

In [43]:
from sklearn.model_selection import train_test_split

In [45]:
df.columns

Index(['Unnamed: 0', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Ticket', 'Fare', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [47]:
X = df[['Unnamed: 0', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Ticket', 'Fare', 'Embarked_Q', 'Embarked_S']]
y = df['Survived']

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=123, stratify=df['Survived'])

In [54]:
print(
    ((df["Survived"] == 1).sum() / df.shape[0]).round(2),
    ((y_train == 1).sum() / y_train.shape[0]).round(2),
    ((y_test == 1).sum() / y_test.shape[0]).round(2),
)

0.42 0.42 0.42